import { TopBar } from "@/components/TopBar";
import "./globals.css";
import {Afacad_Flux} from 'next/font/google'

const afacad = Afacad_Flux({
  subsets:['latin'],
  weight:['400','500','600','700','800','900'],
  display: 'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${afacad.className}`}>
      <TopBar/>
      {children}
      </body>
    </html>
  );
}
